#!/bin/sh

set -e

# Get current branch name, preferring GitHub Actions env var if available
CURRENT_BRANCH=${GITHUB_REF_NAME:-$(git branch --show-current)}

[ "${CURRENT_BRANCH}" = main ] || SUFFIX="-dev"
cat << EOF > "${GITHUB_OUTPUT}"
image=ghcr.io/${GITHUB_REPOSITORY_OWNER}/$(basename "${PWD}")${SUFFIX}
version=$("$(dirname $0)"/version)
EOF
