[package]
name = "maestro-symphony"
version = "0.0.1"
edition = "2024"
authors = ["jharper@gomaestro.org"]

[dependencies]
thiserror = "2.0.12"
tempfile = "3.19.1"
rocksdb = "0.23.0"
gasket = { version = "^0.5", features = ["derive"] }
tokio = { version = "1.45.0", features = ["rt", "rt-multi-thread", "net", "io-util"] }
hex = "0.4.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
config = { version = "0.15.11", default-features = false, features = ["toml", "json"] }
socket2 = "0.5.9"
serde = "1.0.219"
async-trait = "0.1.88"
maestro-symphony-macros = { path = "./macros" }
bitcoin = { version = "0.32.3", features = ["serde", "rand-std"] }
indexmap = "2.9.0"
itertools = "0.14.0"
clap = { version = "4.5.39", features = ["derive"] }

# runes
ordinals = "0.0.15"

[workspace]
members = ["macros"]
