services:
  bitcoin-node:
    image: bitcoin/bitcoin:29
    command:
      - -printtoconsole
      - -txindex
      - -port=8333
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcport=8332
      - -rpcthreads=1
      - -rpcuser=symphony
      - -rpcpassword=symphony
      - -datadir=/srv/bitcoin/node
      - -deprecatedrpc=warnings
      - -rest
      - -regtest
    ports:
      - "8333:8333" # P2P port
      - "8332:8332" # RPC port
    volumes:
      - ./tmp/bitcoin-data:/srv/bitcoin/node
    logging:
      options:
        max-size: "30m"
        max-file: "2"
    restart: unless-stopped

  symphony:
    build:
      context: .
    command:
      - /etc/symphony/config.toml
      - run
    environment:
      - RUST_LOG=info
    ports:
      - "8080:8080"
    volumes:
      - ./examples/regtest.toml:/etc/symphony/config.toml
      - ./tmp/symphony-data:/srv/symphony
    depends_on:
      - bitcoin-node
    logging:
      options:
        max-size: "30m"
        max-file: "2"
    restart: unless-stopped

volumes:
  bitcoin-data:
  symphony-data:
