db_path = "tmp/symphony"

[sync.node]
p2p_address = "localhost:8333"
rpc_address = "http://localhost:8332"
rpc_user = "..." // insert RPC credentials
rpc_pass = "..." // insert RPC credentials

[sync]
network = "mainnet"
safe_mode = true
max_rollback = 32
mempool = true

[sync.indexers]
transaction_indexers = [
    { type = "TxCountByAddress" },
    { type = "UtxosByAddress" },
    { type = "Runes", start_height = 840000 }
]

[server]
address = "0.0.0.0:8080"
