db_path = "tmp/symphony"

[sync.node]
p2p_address = "bitcoin-node:8333"
rpc_address = "http://bitcoin-node:8332"
rpc_user = "symphony"
rpc_pass = "symphony"

[sync]
network = "mainnet"
safe_mode = true
max_rollback = 32
mempool = true

[sync.indexers]
transaction_indexers = [
    { type = "UtxosByAddress" },
    { type = "Runes", start_height = 840000 }
]

[server]
address = "0.0.0.0:8080"
