db_path = "/srv/symphony"

[sync.node]
p2p_address = "bitcoin-node:8333"
rpc_address = "http://bitcoin-node:8332"
# RPC user
rpc_user = "symphony"
# RPC password
rpc_pass = "symphony"

[sync]
network = "regtest"
max_rollback = 32
mempool = true

[sync.indexers]
transaction_indexers = [
    { type = "TxCountByAddress" },
    { type = "UtxosByAddress" },
    { type = "Runes", index_activity = true }
]

[server]
address = "0.0.0.0:8080"
