db_path = "tmp/symphony"

[sync.node]
p2p_address = "bitcoin-node:8333"
rpc_address = "http://bitcoin-node:8332"
# RPC user
rpc_user = "..."
# RPC password
rpc_pass = "..."

[sync]
network = "regtest"
safe_mode = true
max_rollback = 32
mempool = true

[sync.indexers]
transaction_indexers = [
    { type = "TxCountByAddress" },
    { type = "UtxosByAddress" },
    { type = "Runes" }
]

[server]
address = "0.0.0.0:8080"
