db_path = "/srv/symphony"

# [storage]
# Size in GB to bound RocksDB memory usage (default 25% of memory + ~2% of DB size)
# rocksdb_memory_budget = 2.0

[sync.node]
p2p_address = "bitcoin-node:8333"
rpc_address = "http://bitcoin-node:8332"
# RPC user
rpc_user = "symphony"
# RPC password
rpc_pass = "symphony"

[sync]
network = "testnet4"
max_rollback = 256
mempool = true
# Size in GB to bound UTxO cache (0 = disabled) (default 40% of memory)
# utxo_cache_size = 0.5

[sync.indexers]
transaction_indexers = [
    { type = "TxCountByAddress" },
    { type = "UtxosByAddress" },
    { type = "Runes", start_height = 30562, index_activity = true }
]

[server]
address = "0.0.0.0:8080"
