db_path = "tmp/symphony"

[sync]
node_address = "localhost:8333"
network = "testnet"
safe_mode = true
max_rollback = 1

[sync.indexers]
transaction_indexers = [
    { type = "TxCountByAddress" },
    { type = "Runes", start_height = 35062 }
]
