db_path = "tmp/symphony"

[sync]
node_address = "localhost:8333"
node_rpc_address = "http://localhost:8332"
node_rpc_user = "..."
node_rpc_pass = "..."
network = "testnet"
safe_mode = true
max_rollback = 32

[sync.indexers]
transaction_indexers = [
    { type = "UtxosByAddress" },
    { type = "Runes", start_height = 30562 }
]

[server]
address = "0.0.0.0:8080"
