db_path = "tmp/symphony"

[sync.node]
p2p_address = "localhost:8333"
rpc_address = "http://localhost:8332"
rpc_user = "maestro"
rpc_pass = "maestro"

[sync]
network = "testnet"
safe_mode = true
max_rollback = 32

[sync.indexers]
transaction_indexers = [
    { type = "UtxosByAddress" },
    { type = "Runes", start_height = 30562 }
]

[server]
address = "0.0.0.0:8080"
