db_path = "tmp/symphony"

[sync]
node_address = "localhost:8333"
network = "testnet"
safe_mode = true
max_rollback = 1

[sync.indexers]
transaction_indexers = [
    { type = "UtxosByAddress" },
    { type = "Runes", start_height = 30562, index_activity = true }
]

[server]
address = "0.0.0.0:8080"
