db_path = "tmp/symphony"

[storage]
# Total memory budget for RocksDB in GB (default 30% of available system memory)
rocksdb_memory_budget = 2.0

[sync.node]
p2p_address = "bitcoin-node:8333"
rpc_address = "http://bitcoin-node:8332"
# RPC user
rpc_user = "..."
# RPC password
rpc_pass = "..."

[sync]
network = "testnet4"
max_rollback = 256
mempool = true
# Size in GB to use for UTxO cache (0 = disabled, default 10% of memory)
utxo_cache_size = 0.5

[sync.indexers]
transaction_indexers = [
    { type = "TxCountByAddress" },
    { type = "UtxosByAddress" },
    { type = "Runes", start_height = 30562, index_activity = true }
]

[server]
address = "0.0.0.0:8080"
